# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


version: '2'

volumes:
  orderer0.trappiste.fr:
  orderer1.trappiste.fr:
  orderer2.trappiste.fr:
  peer0.magasin.trappiste.fr:
  peer1.magasin.trappiste.fr:
  peer0.chimay.fournisseur.be:
  peer1.chimay.fournisseur.be:

networks:
  trappiste-network:

services:

  orderer0.trappiste.fr:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    container_name: orderer0.trappiste.fr
    environment:
      - ORDERER_GENERAL_LISTENPORT=7050
      - FABRIC_LOGGING_SPEC=ERROR
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
     
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

    networks:
      - trappiste-network
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/tls/:/var/hyperledger/orderer/tls
      - orderer0.trappiste.fr:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 7050:7050    

  orderer1.trappiste.fr:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    container_name: orderer1.trappiste.fr
    environment:
      - ORDERER_GENERAL_LISTENPORT=8050
      - FABRIC_LOGGING_SPEC=ERROR
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
     
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/trappiste.fr/orderers/orderer1.trappiste.fr/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/trappiste.fr/orderers/orderer1.trappiste.fr/tls/:/var/hyperledger/orderer/tls
        - orderer1.trappiste.fr:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 8050:8050        
    networks:
      - trappiste-network

  orderer2.trappiste.fr:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    container_name: orderer2.trappiste.fr
    environment:
      - ORDERER_GENERAL_LISTENPORT=9050
      - FABRIC_LOGGING_SPEC=ERROR
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
     
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

    networks:
      - trappiste-network
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trappiste.fr/orderers/orderer2.trappiste.fr/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trappiste.fr/orderers/orderer2.trappiste.fr/tls/:/var/hyperledger/orderer/tls
      - orderer2.trappiste.fr:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 9050:9050    



  peer0.magasin.trappiste.fr:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    command: peer node start  
    container_name: peer0.magasin.trappiste.fr
    environment:
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer0.magasin.trappiste.fr
      - CORE_PEER_ADDRESS=peer0.magasin.trappiste.fr:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      #ChaineCode
      - CORE_PEER_CHAINCODEADDRESS=peer0.magasin.trappiste.fr:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_CHAINCODE_LOGGING_SHIM=ERROR
      - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
      #GOSSIP
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.magasin.trappiste.fr:7061
      #- CORE_PEER_GOSSIP_ENDPOINT=peer0.magasin.trappiste.fr:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.magasin.trappiste.fr:7051 ## utile pour trouver un peer depuis une app sinon avec l'app je peux pas me connecter :/
      
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      #MSPid
      - CORE_PEER_LOCALMSPID=MagasinMSP
      #VM
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_trappiste-network #important le _trappiste-network sinon le chainecode marche pas
      #ERROR
      - FABRIC_LOGGING_SPEC=ERROR
      #TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/tls:/etc/hyperledger/fabric/tls
        - peer0.magasin.trappiste.fr:/var/hyperledger/production
    networks:
      - trappiste-network
    ports:
      - 7051:7051   

  peer1.magasin.trappiste.fr:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    command: peer node start  
    container_name: peer1.magasin.trappiste.fr
    environment:
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer1.magasin.trappiste.fr
      - CORE_PEER_ADDRESS=peer1.magasin.trappiste.fr:7061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
      #ChaineCode
      - CORE_PEER_CHAINCODEADDRESS=peer1.magasin.trappiste.fr:7062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
      - CORE_CHAINCODE_LOGGING_SHIM=ERROR
      - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
      #GOSSIP
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.magasin.trappiste.fr:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.magasin.trappiste.fr:7061
      
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      #MSPid
      - CORE_PEER_LOCALMSPID=MagasinMSP
      #VM
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_trappiste-network #important le _trappiste-network sinon le chainecode marche pas
      #ERROR
      - FABRIC_LOGGING_SPEC=ERROR
      #TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/magasin.trappiste.fr/peers/peer1.magasin.trappiste.fr/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/magasin.trappiste.fr/peers/peer1.magasin.trappiste.fr/tls:/etc/hyperledger/fabric/tls
        - peer1.magasin.trappiste.fr:/var/hyperledger/production
    networks:
      - trappiste-network
    ports:
      - 7061:7061   

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=ERROR #Carreful in production have to comment it
      #- FABRIC_LOGGING_SPEC=ERROR
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.magasin.trappiste.fr:7051
      - CORE_PEER_LOCALMSPID=MagasinMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/magasin.trappiste.fr/users/Admin@magasin.trappiste.fr/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincodeTrappiste/:/opt/gopath/src/github.com/chaincode
        - ./chaincodeTrappisteFournisseur/:/opt/gopath/src/github.com/chaincode-fournisseur
        - ./chaincodeTrappisteDependance/:/opt/go/src/github.com/hyperledger/fabric/core/chaincode/shim/ext/ 
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./scripts/:/tmp/scripts/
    networks:
      - trappiste-network

  ca0:
      image: hyperledger/fabric-ca:$IMAGE_TAG
      environment:
        - FABRIC_CA_SERVER_CA_NAME=ca.magasin.trappiste.fr  #ca0_orga1
        - FABRIC_LOGGING_SPEC=ERROR
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.magasin.trappiste.fr-cert.pem
        # se trouve dans : crypto-config/peerOrganizations/orga1.trappiste.fr/ca/
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA1_PRIVATE_KEY}
        - FABRIC_CA_SERVER_PORT=7054
        - FABRIC_CA_CLIENT_TLS_CERTFILES=/etc/hyperledger/fabric-ca-server-config/ca.magasin.trappiste.fr-cert.pem
      ports:
        - "7054:7054"
      command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.magasin.trappiste.fr-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA1_PRIVATE_KEY} -b admin:adminpw -d'
      volumes:
        - ./crypto-config/peerOrganizations/magasin.trappiste.fr/ca/:/etc/hyperledger/fabric-ca-server-config
      container_name: ca.magasin.trappiste.fr 
      networks:
        - trappiste-network      

#############   FOURNISSEUR Â  #################

  peer0.chimay.fournisseur.be:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    command: peer node start  
    container_name: peer0.chimay.fournisseur.be
    environment:
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer0.chimay.fournisseur.be
      - CORE_PEER_ADDRESS=peer0.chimay.fournisseur.be:1001
      - CORE_PEER_LISTENADDRESS=0.0.0.0:1001
      #ChaineCode
      - CORE_PEER_CHAINCODEADDRESS=peer0.chimay.fournisseur.be:1002
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:1002
      - CORE_CHAINCODE_LOGGING_SHIM=ERROR
      - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
      #GOSSIP
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.chimay.fournisseur.be:1011
      #- CORE_PEER_GOSSIP_ENDPOINT=peer0.chimay.fournisseur.be:1001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.chimay.fournisseur.be:1001 ## utile pour trouver un peer depuis une app sinon avec l'app je peux pas me connecter :/
      
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      #MSPid
      - CORE_PEER_LOCALMSPID=ChimayMSP
      #VM
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_trappiste-network #important le _trappiste-network sinon le chainecode marche pas
      #ERROR
      - FABRIC_LOGGING_SPEC=ERROR
      #TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/chimay.fournisseur.be/peers/peer0.chimay.fournisseur.be/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/chimay.fournisseur.be/peers/peer0.chimay.fournisseur.be/tls:/etc/hyperledger/fabric/tls
        - peer0.chimay.fournisseur.be:/var/hyperledger/production
    networks:
      - trappiste-network
    ports:
      - 1001:1001   

  peer1.chimay.fournisseur.be:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    command: peer node start  
    container_name: peer1.chimay.fournisseur.be
    environment:
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer1.chimay.fournisseur.be
      - CORE_PEER_ADDRESS=peer1.chimay.fournisseur.be:1011
      - CORE_PEER_LISTENADDRESS=0.0.0.0:1011
      #ChaineCode
      - CORE_PEER_CHAINCODEADDRESS=peer1.chimay.fournisseur.be:1012
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:1012
      - CORE_CHAINCODE_LOGGING_SHIM=ERROR
      - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
      #GOSSIP
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.chimay.fournisseur.be:1001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.chimay.fournisseur.be:1011
      
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      #MSPid
      - CORE_PEER_LOCALMSPID=ChimayMSP
      #VM
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_trappiste-network #important le _trappiste-network sinon le chainecode marche pas
      #ERROR
      - FABRIC_LOGGING_SPEC=ERROR
      #TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/chimay.fournisseur.be/peers/peer1.chimay.fournisseur.be/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/chimay.fournisseur.be/peers/peer1.chimay.fournisseur.be/tls:/etc/hyperledger/fabric/tls
        - peer1.chimay.fournisseur.be:/var/hyperledger/production
    networks:
      - trappiste-network
    ports:
      - 1011:1011  

  ca1:
      image: hyperledger/fabric-ca:$IMAGE_TAG
      environment:
        - FABRIC_CA_SERVER_CA_NAME=ca.chimay.fournisseur.be  #ca0_orga1
        - FABRIC_LOGGING_SPEC=ERROR
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.chimay.fournisseur.be-cert.pem
        # se trouve dans : crypto-config/peerOrganizations/orga1.trappiste.fr/ca/
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA2_PRIVATE_KEY}
        - FABRIC_CA_SERVER_PORT=1054
        - FABRIC_CA_CLIENT_TLS_CERTFILES=/etc/hyperledger/fabric-ca-server-config/ca.chimay.fournisseur.be-cert.pem
      ports:
        - "1054:1054"
      command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.chimay.fournisseur.be-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA2_PRIVATE_KEY} -b admin:adminpw -d'
      volumes:
        - ./crypto-config/peerOrganizations/chimay.fournisseur.be/ca/:/etc/hyperledger/fabric-ca-server-config
      container_name: ca.chimay.fournisseur.be 
      networks:
        - trappiste-network         